- host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/sample-1"
        backend:
          service:
            name: sample-1
            port:
              number: 3000